### ISSUE TITLE
Insert tips for contributors on statement page

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#195]
Here, tips will be short advices for contributors on how to analyse properly one statement or how to choose the correct verdict.
The differences between 'tips' and Help pages are:

1) the statement type may require a certain set of tips; for example, a statement based on a picture should be accompanied by tips on how to verify if the picture is falsified or taken out of context;

2) tips are displayed on the same page with statement context and statement scope, creating a singular workplace for the contributor, compared to the 'developer mode' some of us are used to (when we work with 2 monitors and we keep at least 2 browser windows opened at the same time, one for the statement page and another one for a particular Help page). The place where we display such tips to the user must take into account the [Fitts's Law](https://lawsofux.com/fittss-law) and the [Hick's Law](https://lawsofux.com/hicks-law).

3) tips can vary from contributor to contributor, depending on his/her proficiency and experience. For now, there is no way to tell the difference between beginners and experienced users (contributors), but in the future it might worth have it.

**A first set of tips is the following:**
> 1) Dacă un comentariu este atribuit unui politician, atunci sursa comentariului trebuie să fie una oficială (transcriere oficială de pe site-ul partidului sau paginile de social media ale politicianului).
>
> 2) Dacă o informație de pe internet pare suspectă, atunci primul pas recomandat este să analizezi comentariile care o însoțesc. Următorul pas este să cauți personalități menționate în acea știre și să le contactezi pentru a confirma știrea.
>
> 3) Pentru a evita creșterea traficului către știri false, este recomandat să folosești unelte de arhivă web (Wayback Machine, Perma CC). În acest fel, se poate păstra și o referință ulterioară în caz că știrea căutată inițial se modifică sau dispare.
> 
> 4) Dacă faci o greșeală de analiză și notezi o afirmație politică cu o valoare greșită de adevăr, atunci acest lucru trebuie corectat și menționat în articolul original care însoțește acea afirmație.
> 
> 5) Clarificările și actualizările aduse unei analize politice trebuie notate ca atare la sfârșitul articolului publicat. Data și motivul actualizărilor trebuie menționate de asemenea.
> 

Another type of tips is the **list of trustworthy websites** for:
- Romanian statistics
- European statistics
- the Romanian constitution
- etc.

**UPDATE**
Tips to be displayed on _Add statement page_, under **surse** textfield: 1)
Tips to be displayed on _a statement page_, near the **Răspunsul tău** textarea: 2), 4) and 5).

**Comment by CatalinFrancu** [comment]
Some random thoughts:

Off-topic statements, fictitious statements, poorly formatted statements etc. can and should be flagged and closed. The reviewer who closes a statement can leave publicly visible feedback with the reason for closing the statement. This is worth remembering, but I agree that it is even better to prevent the accumulation of undesirable statements.

(Difference #3) Some games I have played (WoW among them) show plenty of tips at the beginning, with each tip being shown just once. The player has the option to reset the tip status and start receiving them all over again. There is no individual _dismiss_ checkbox, but we could have one for each tip if we wanted to.

(Tip #2) Even if the statement is determined to be fictitious, it might be worth including it. We could credit it to the news source, tag it as fake news and give it a false verdict (or a new kind of verdict). This helps establish the lack of credibility of that news source.

(Tip #3) Should we require contributors to _always_ use perma.cc, as opposed to just copy-and-pasting the URL? Should we instead allow them to copy-and-paste the plain URL, then handle the perma.cc business ourselves via the API?

(Tip #4) Once we have more users, the person who writes the analysis and the person who accepts the answers and gives a verdict to the statement should be two different people. Even if they both have the privilege to do so, cross-examination is good.

(Tip #5) We have the version history tool. It does not have a reason field, but we can add one. Also, once an answer is accepted and the statement receives a verdict, both the statement and the answer are protected and only moderators can make further edits. The original authors can no longer edit them (unless they are moderators).

**Comment by sandriu** [comment]
> (Tip 3) Should we require contributors to always use perma.cc, as opposed to just copy-and-pasting the URL? Should we instead allow them to copy-and-paste the plain URL, then handle the perma.cc business ourselves via the API?

I believe we should let users to copy-and-paste the plain URL, then handle the perma.cc business ourselves. I do not expect the majority of our contributors to be familiar with perma.cc and other similar options.

**Comment by sandriu** [comment]
A first candidate in terms of UI elements used to display these tips on the statement page is the [Material Design side sheet](https://material.io/components/sheets-side), which is an area anchored to the right edge of the page on desktops and to the bottom edge of the page on mobile. The side sheet could remain visible while users interact with primary content or it could be dismissed by the user. I'm working on a wireframe for this.

**Comment by sandriu** [comment]
The wireframes for statement page's side sheet are below. 
First one represents the initial state, when the side sheet is expanded and the user can choose to hide it next time he/she visits this page:

> ![20201221_155244](https://user-images.githubusercontent.com/1265882/102785381-91855a80-43a6-11eb-8590-5191506009f8.jpg)

Second wireframe represents the 'collapsed' state for the side sheet, where the user has previously opted not to see it again, but if he/she changes his/her mind, then he/she can click on the lightbulb icon displayed on the right margin of the page to expand the side sheet:
![20201221_155351](https://user-images.githubusercontent.com/1265882/102785888-56cff200-43a7-11eb-9b4d-ab73cff649f0.jpg)

Anatomy for this side sheet area:
- position: on desktop it is sticked to the right margin of the page, on mobile it is sticked to the bottom margin
- height: the whole height of the page, except for the navigation bar (the dark area whene the platform logo is placed)
- width: on mobile it has full width, on desktop it has 20-30% of page width (without overlapping the main content, i.e. the 'Răspunsul tău' area)
- on top it has a title ('Sugestii de analiză' might work for now) and a close button in the shape of an X

**Comment by CatalinFrancu** [comment]
Once I merge the code, there is one bug remaining on mobile. If the side sheet is tall enough, the content below the fold becomes unreachable. I tried setting `overflow-y: scroll`, but then the light bulb becomes invisible (when the side sheet is minimized).

**Comment by sandriu** [comment]
> Once I merge the code, there is one bug remaining on mobile. If the side sheet is tall enough, the content below the fold becomes unreachable. I tried setting `overflow-y: scroll`, but then the light bulb becomes invisible (when the side sheet is minimized).

@CatalinFrancu I will try to fix this bug.

**Comment by sandriu** [comment]
When the side sheet is expanded to the right margin of the browser window, we want to avoid the scenario in which 2 scroll bars appear: one for the page and another one for the side sheet. So the `overflow-y: scroll` is not the solution for making visible the whole content of the side sheet.
We should rather display the side sheet content in tabs, to avoid making it too long.

**Comment by sandriu** [comment]
This is how the side sheet looks now on mobile:
![dignitas-side-sheet-mobile](https://user-images.githubusercontent.com/1265882/107952382-5c5e4880-6fa2-11eb-8e5b-39031fc383f5.jpg)

The mobile keyboard occupies about one third of the screen, the side sheet occupies more than 50% of the screen and there is no room left for editing the answer (without closing the side sheet). So the side sheet should be displayed on 100% of the screen on mobiles (and closed by the user after he/shes reads its content). Ideally, it should be a modal window (with scrim).

**Comment by CatalinFrancu** [comment]
Done! Please take a look. Some known issues:

- We hide the backdrop (scrim) so that the user can still interact with the page. Sadly, this also applies to the other modal present on the page: the flagging modal.
- Similarly, we keep the scrollbar to `auto` so that the user can still scroll the main page. This means that the page is also scrollable while the flagging modal is up.

These problems only occur on wide screens (>1680px).

**Comment by sandriu** [comment]
On desktop, I clicked on the lightbulb icon ('Your answer' area) and saw, for a second, the scrim, then it disappeared. There is no need for scrim on desktop for the side sheet. For the flagging modal (flag action) the scrim still appears.
